# Generated by Django 5.2.5 on 2025-09-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='is_claimed',
            field=models.BooleanField(default=True),
        ),
    ]
