# Generated by Django 5.2.5 on 2025-09-18 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        # Step 1: Make user field nullable and remove primary_key=True
        migrations.AlterField(
            model_name='provider',
            name='user',
            field=models.OneToOneField(
                blank=True,
                help_text='The user who owns this provider account (null for unclaimed listings)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                unique=True
            ),
        ),
        
        # Step 2: Change is_claimed default to False
        migrations.AlterField(
            model_name='provider',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
    ]