# Generated by Django 5.2.5 on 2025-09-18 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_claim'),
    ]

    operations = [
        # Step 1: Add new id field as primary key
        migrations.AddField(
            model_name='provider',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        
        # Step 2: Remove primary key from user field and make it nullable
        migrations.AlterField(
            model_name='provider',
            name='user',
            field=models.OneToOneField(
                blank=True,
                help_text='The user who owns this provider account (null for unclaimed listings)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                unique=True
            ),
        ),
        
        # Step 3: Change is_claimed default to False
        migrations.AlterField(
            model_name='provider',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
    ]