# Generated by Django 5.2.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_provider_nullable_user_and_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='phone_verification_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='phone_verification_deferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='phone_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveConstraint(
            model_name='claim',
            name='unique_active_claim_per_user_provider',
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'approved'])), fields=('provider', 'claimant'), name='unique_active_claim_per_user_provider'),
        ),
    ]