# Generated by Django 4.2.24 on 2025-10-04 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_provider_nullable_user_and_claim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='day_of_week',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], help_text='Day of the week for this availability slot', max_length=10),
        ),
        migrations.AlterField(
            model_name='availability',
            name='end_time',
            field=models.TimeField(help_text='Time when provider stops being available (must be after start_time)'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Whether the provider is actually available during this time slot'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='provider',
            field=models.ForeignKey(help_text='The provider whose schedule this represents', on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='api.provider'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start_time',
            field=models.TimeField(help_text='Time when provider becomes available (must be before end_time)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.category'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(help_text='Category this service belongs to (e.g., Plumbing, Electrical)', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.category'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of what this service includes', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this service is currently being offered'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text='Service name (e.g., "Emergency Plumbing Repair")', max_length=150),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Service price (interpretation depends on price_type)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Per Hour'), ('daily', 'Per Day'), ('quote', 'Quote Required')], default='quote', help_text='How the price is charged (fixed, hourly, daily, or requires quote)', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(help_text='The provider offering this service', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.provider'),
        ),
    ]
