# Generated by Django 5.0.1 on 2025-09-19 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_populate_search_vectors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='search_vector',
        ),
    ]
