# Generated by Django 5.0.1 on 2025-09-21 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_notification_system'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='messagethread',
            name='unique_customer_provider_thread',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='api_message_thread__045a22_idx',
            old_name='api_message_thread_6f4d5e_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='api_message_sender__eea5d5_idx',
            old_name='api_message_sender_7e8f9a_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='api_notific_user_id_5b04a6_idx',
            old_name='api_notific_user_id_9b5c5f_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='api_notific_user_id_16328d_idx',
            old_name='api_notific_user_id_af7a8d_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='api_notific_created_238c70_idx',
            old_name='api_notific_created_2a1b3c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='messagethread',
            unique_together={('customer', 'provider')},
        ),
    ]
