# Generated by Django 5.0.1 on 2025-09-22 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fix_review_provider_fk'),
        ('api', '0013_remove_messagethread_unique_customer_provider_thread_and_more'),
    ]

    operations = [
    ]
